GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ann Kuu",
    "number": 11111111
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": " ",
    "number": 56450
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": 56450
}